version: "3.3"

services:
  database:
    container_name: orcamento_familiar_api
    image: postgres:13.5
    restart: always
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=ofapi
      - POSTGRES_USER=ofapi
      - POSTGRES_DB=dbapi
    ports:
      - 5434:5432