# Generated by Django 3.2.11 on 2022-01-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('mes', models.IntegerField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('modificacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('descricao', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('mes', models.IntegerField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('modificacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('descricao', 'mes')},
            },
        ),
    ]
